language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
install:
  - pear install PHP_CodeSniffer
  - phpenv rehash
script:
  - find . -name '*.php' -print0 | xargs -0 -n1 php -lf || true # Allow failures for now
  - phpcs --standard=PSR1,PSR2 --extensions=php . || true # Allow failures for now
